tap "frontierlabs/infinitekey", "https://github.frontierlabs.nadenso.com/FrontierLabs/homebrew-infinitekey/"
tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/versions"
tap "caskroom/cask"
cask "xquartz"
brew "autoconf"
brew "automake"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "libffi"
brew "pcre"
brew "glib"
brew "pixman"
brew "coreutils"
brew "ctags"
brew "ddrescue"
brew "dhcpdump"
brew "dialog"
brew "direnv"
brew "docker-machine-driver-xhyve"
brew "ffmpeg"
brew "gcc@4.9"
brew "gnu-sed"
brew "gnu-tar"
brew "pkg-config"
brew "gobject-introspection"
brew "groovy"
brew "harfbuzz"
brew "jq"
brew "kubernetes-cli"
brew "kops"
brew "kubectx", args: ["with-short-names"]
brew "kubernetes-helm"
brew "libksba"
brew "readline"
brew "libpqxx"
brew "libtool"
brew "libyaml"
brew "mas"
brew "minicom"
brew "node"
brew "pango"
brew "pyenv"
brew "pyqt", args: ["without-python3"]
brew "rbenv"
brew "rrdtool"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "frontierlabs/infinitekey/gcc-arm-none-eabi-483"
brew "frontierlabs/infinitekey/kconfig-frontends"
cask "adobe-acrobat-reader"
cask "alfred"
cask "atom"
cask "beyond-compare"
cask "box-sync"
cask "docker"
cask "dropbox"
cask "evernote"
cask "google-chrome"
cask "java"
cask "parallels"
cask "postman"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "virtualbox"
cask "visual-studio-code"
cask "vmware-horizon-client"
cask "vnc-viewer"
cask "ynab"
cask "frontierlabs/infinitekey/nordic-nrf5x-command-line-tools"
cask "frontierlabs/infinitekey/segger-jlink"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Wunderlist", id: 410628904
mas "Xcode", id: 497799835
